### ISSUE TITLE
Do we still need the data in the `input-data` subdir?

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/cassandra#42]
This was a holdover from the first experiment the system was used in.  Most of the data in there looks like it was used by the old water codes, so I think it's probably obsolete.  @crvernon, @calebbraun, do you know if we are using this data for anything?

**Comment by calebbraun** [comment]
I don't think we are. It seems our philosophy with this iteration of the system is that each component is responsible for describing its necessary inputs and where to find them, so we will not need to point to a specific directory by default.

**Comment by rplzzz** [comment]
That's what I thought too.  I'll remove it in the branch I'm working on.
