### ISSUE TITLE
Add unit testing

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/cassandra#8]
We have a couple of test codes for various subsystems.  We should convert these to proper unit tests using the `unittest` module, and we should improve the unit test coverage.  There are some things we can't test without running the entire calculation, but even there we might be able to put together some dummy data sets to at least verify that the data is being handled correctly.

**Comment by calebbraun** [comment]
Testing coverage could still be improved, but with #26, can we consider this resolved?

**Comment by rplzzz** [comment]
Yep, I think this is a good start.  Basically, we'll add new tests as we add new features, and whenever we have to debug something that's gone wrong, we'll add tests to detect if the bug ever creeps back in.
